// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: vendor_adapter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status baku (Normalized Status) agar Transfer Service tidak perlu tahu bahasa Vendor
type TransferStatus int32

const (
	TransferStatus_UNKNOWN TransferStatus = 0
	TransferStatus_PENDING TransferStatus = 1 // Transaksi sedang diproses, tunggu Webhook atau lakukan Inquiry
	TransferStatus_SUCCESS TransferStatus = 2 // Uang berhasil pindah
	TransferStatus_FAILED  TransferStatus = 3 // Transaksi gagal, uang harus dikembalikan (Saga Rollback)
)

// Enum value maps for TransferStatus.
var (
	TransferStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "SUCCESS",
		3: "FAILED",
	}
	TransferStatus_value = map[string]int32{
		"UNKNOWN": 0,
		"PENDING": 1,
		"SUCCESS": 2,
		"FAILED":  3,
	}
)

func (x TransferStatus) Enum() *TransferStatus {
	p := new(TransferStatus)
	*p = x
	return p
}

func (x TransferStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_vendor_adapter_proto_enumTypes[0].Descriptor()
}

func (TransferStatus) Type() protoreflect.EnumType {
	return &file_vendor_adapter_proto_enumTypes[0]
}

func (x TransferStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferStatus.Descriptor instead.
func (TransferStatus) EnumDescriptor() ([]byte, []int) {
	return file_vendor_adapter_proto_rawDescGZIP(), []int{0}
}

// Request untuk melakukan transfer
type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // ID Transaksi unik dari Transfer Service (Correlation ID)
	SourceAccount string                 `protobuf:"bytes,2,opt,name=source_account,json=sourceAccount,proto3" json:"source_account,omitempty"` // Rekening pengirim
	TargetAccount string                 `protobuf:"bytes,3,opt,name=target_account,json=targetAccount,proto3" json:"target_account,omitempty"` // Rekening tujuan di bank/vendor lain
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`                                  // Nominal transfer
	BankCode      string                 `protobuf:"bytes,5,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`                // Kode bank/biller tujuan (opsional jika sudah fix)
	Narration     string                 `protobuf:"bytes,6,opt,name=narration,proto3" json:"narration,omitempty"`                              // Catatan / Berita transfer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_vendor_adapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_adapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_vendor_adapter_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransferRequest) GetSourceAccount() string {
	if x != nil {
		return x.SourceAccount
	}
	return ""
}

func (x *TransferRequest) GetTargetAccount() string {
	if x != nil {
		return x.TargetAccount
	}
	return ""
}

func (x *TransferRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *TransferRequest) GetNarration() string {
	if x != nil {
		return x.Narration
	}
	return ""
}

// Response hasil eksekusi transfer dari Vendor
type TransferResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionId     string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status            TransferStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=banking.adapter.v1.TransferStatus" json:"status,omitempty"`
	VendorReferenceId string                 `protobuf:"bytes,3,opt,name=vendor_reference_id,json=vendorReferenceId,proto3" json:"vendor_reference_id,omitempty"` // Nomor referensi asli dari sistem Vendor (jika berhasil)
	ErrorCode         string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`                           // Kode error spesifik jika gagal (di-mapping dari vendor)
	ErrorMessage      string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                  // Pesan error dari vendor
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_vendor_adapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_adapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_vendor_adapter_proto_rawDescGZIP(), []int{1}
}

func (x *TransferResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransferResponse) GetStatus() TransferStatus {
	if x != nil {
		return x.Status
	}
	return TransferStatus_UNKNOWN
}

func (x *TransferResponse) GetVendorReferenceId() string {
	if x != nil {
		return x.VendorReferenceId
	}
	return ""
}

func (x *TransferResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TransferResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request untuk mengecek status transaksi (Inquiry)
type StatusRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionId     string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`               // ID Transaksi internal kita
	VendorReferenceId string                 `protobuf:"bytes,2,opt,name=vendor_reference_id,json=vendorReferenceId,proto3" json:"vendor_reference_id,omitempty"` // (Opsional) Referensi vendor jika kita menyimpannya
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_vendor_adapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_adapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_vendor_adapter_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *StatusRequest) GetVendorReferenceId() string {
	if x != nil {
		return x.VendorReferenceId
	}
	return ""
}

// Response hasil cek status
type StatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionId     string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status            TransferStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=banking.adapter.v1.TransferStatus" json:"status,omitempty"`
	VendorReferenceId string                 `protobuf:"bytes,3,opt,name=vendor_reference_id,json=vendorReferenceId,proto3" json:"vendor_reference_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_vendor_adapter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_adapter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_vendor_adapter_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *StatusResponse) GetStatus() TransferStatus {
	if x != nil {
		return x.Status
	}
	return TransferStatus_UNKNOWN
}

func (x *StatusResponse) GetVendorReferenceId() string {
	if x != nil {
		return x.VendorReferenceId
	}
	return ""
}

var File_vendor_adapter_proto protoreflect.FileDescriptor

const file_vendor_adapter_proto_rawDesc = "" +
	"\n" +
	"\x14vendor_adapter.proto\x12\x12banking.adapter.v1\"\xd9\x01\n" +
	"\x0fTransferRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12%\n" +
	"\x0esource_account\x18\x02 \x01(\tR\rsourceAccount\x12%\n" +
	"\x0etarget_account\x18\x03 \x01(\tR\rtargetAccount\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1b\n" +
	"\tbank_code\x18\x05 \x01(\tR\bbankCode\x12\x1c\n" +
	"\tnarration\x18\x06 \x01(\tR\tnarration\"\xe9\x01\n" +
	"\x10TransferResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12:\n" +
	"\x06status\x18\x02 \x01(\x0e2\".banking.adapter.v1.TransferStatusR\x06status\x12.\n" +
	"\x13vendor_reference_id\x18\x03 \x01(\tR\x11vendorReferenceId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"f\n" +
	"\rStatusRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12.\n" +
	"\x13vendor_reference_id\x18\x02 \x01(\tR\x11vendorReferenceId\"\xa3\x01\n" +
	"\x0eStatusResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12:\n" +
	"\x06status\x18\x02 \x01(\x0e2\".banking.adapter.v1.TransferStatusR\x06status\x12.\n" +
	"\x13vendor_reference_id\x18\x03 \x01(\tR\x11vendorReferenceId*C\n" +
	"\x0eTransferStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032\xca\x01\n" +
	"\x14VendorAdapterService\x12\\\n" +
	"\x0fExecuteTransfer\x12#.banking.adapter.v1.TransferRequest\x1a$.banking.adapter.v1.TransferResponse\x12T\n" +
	"\vCheckStatus\x12!.banking.adapter.v1.StatusRequest\x1a\".banking.adapter.v1.StatusResponseB!Z\x1fbanking-microservices/pkg/pb;pbb\x06proto3"

var (
	file_vendor_adapter_proto_rawDescOnce sync.Once
	file_vendor_adapter_proto_rawDescData []byte
)

func file_vendor_adapter_proto_rawDescGZIP() []byte {
	file_vendor_adapter_proto_rawDescOnce.Do(func() {
		file_vendor_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vendor_adapter_proto_rawDesc), len(file_vendor_adapter_proto_rawDesc)))
	})
	return file_vendor_adapter_proto_rawDescData
}

var file_vendor_adapter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vendor_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vendor_adapter_proto_goTypes = []any{
	(TransferStatus)(0),      // 0: banking.adapter.v1.TransferStatus
	(*TransferRequest)(nil),  // 1: banking.adapter.v1.TransferRequest
	(*TransferResponse)(nil), // 2: banking.adapter.v1.TransferResponse
	(*StatusRequest)(nil),    // 3: banking.adapter.v1.StatusRequest
	(*StatusResponse)(nil),   // 4: banking.adapter.v1.StatusResponse
}
var file_vendor_adapter_proto_depIdxs = []int32{
	0, // 0: banking.adapter.v1.TransferResponse.status:type_name -> banking.adapter.v1.TransferStatus
	0, // 1: banking.adapter.v1.StatusResponse.status:type_name -> banking.adapter.v1.TransferStatus
	1, // 2: banking.adapter.v1.VendorAdapterService.ExecuteTransfer:input_type -> banking.adapter.v1.TransferRequest
	3, // 3: banking.adapter.v1.VendorAdapterService.CheckStatus:input_type -> banking.adapter.v1.StatusRequest
	2, // 4: banking.adapter.v1.VendorAdapterService.ExecuteTransfer:output_type -> banking.adapter.v1.TransferResponse
	4, // 5: banking.adapter.v1.VendorAdapterService.CheckStatus:output_type -> banking.adapter.v1.StatusResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vendor_adapter_proto_init() }
func file_vendor_adapter_proto_init() {
	if File_vendor_adapter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vendor_adapter_proto_rawDesc), len(file_vendor_adapter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vendor_adapter_proto_goTypes,
		DependencyIndexes: file_vendor_adapter_proto_depIdxs,
		EnumInfos:         file_vendor_adapter_proto_enumTypes,
		MessageInfos:      file_vendor_adapter_proto_msgTypes,
	}.Build()
	File_vendor_adapter_proto = out.File
	file_vendor_adapter_proto_goTypes = nil
	file_vendor_adapter_proto_depIdxs = nil
}
