// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: vendor_adapter.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VendorAdapterService_ExecuteTransfer_FullMethodName = "/banking.adapter.v1.VendorAdapterService/ExecuteTransfer"
	VendorAdapterService_CheckStatus_FullMethodName     = "/banking.adapter.v1.VendorAdapterService/CheckStatus"
)

// VendorAdapterServiceClient is the client API for VendorAdapterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==============================================================================
// LAYANAN ADAPTER VENDOR
// ==============================================================================
type VendorAdapterServiceClient interface {
	// Mengeksekusi transfer dari Core/Transfer Service ke Vendor Biller Eksternal
	ExecuteTransfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	// Mengecek status transaksi yang menggantung (Pending) di pihak Vendor
	CheckStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type vendorAdapterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVendorAdapterServiceClient(cc grpc.ClientConnInterface) VendorAdapterServiceClient {
	return &vendorAdapterServiceClient{cc}
}

func (c *vendorAdapterServiceClient) ExecuteTransfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, VendorAdapterService_ExecuteTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorAdapterServiceClient) CheckStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, VendorAdapterService_CheckStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VendorAdapterServiceServer is the server API for VendorAdapterService service.
// All implementations must embed UnimplementedVendorAdapterServiceServer
// for forward compatibility.
//
// ==============================================================================
// LAYANAN ADAPTER VENDOR
// ==============================================================================
type VendorAdapterServiceServer interface {
	// Mengeksekusi transfer dari Core/Transfer Service ke Vendor Biller Eksternal
	ExecuteTransfer(context.Context, *TransferRequest) (*TransferResponse, error)
	// Mengecek status transaksi yang menggantung (Pending) di pihak Vendor
	CheckStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedVendorAdapterServiceServer()
}

// UnimplementedVendorAdapterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVendorAdapterServiceServer struct{}

func (UnimplementedVendorAdapterServiceServer) ExecuteTransfer(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTransfer not implemented")
}
func (UnimplementedVendorAdapterServiceServer) CheckStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckStatus not implemented")
}
func (UnimplementedVendorAdapterServiceServer) mustEmbedUnimplementedVendorAdapterServiceServer() {}
func (UnimplementedVendorAdapterServiceServer) testEmbeddedByValue()                              {}

// UnsafeVendorAdapterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VendorAdapterServiceServer will
// result in compilation errors.
type UnsafeVendorAdapterServiceServer interface {
	mustEmbedUnimplementedVendorAdapterServiceServer()
}

func RegisterVendorAdapterServiceServer(s grpc.ServiceRegistrar, srv VendorAdapterServiceServer) {
	// If the following call panics, it indicates UnimplementedVendorAdapterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VendorAdapterService_ServiceDesc, srv)
}

func _VendorAdapterService_ExecuteTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorAdapterServiceServer).ExecuteTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorAdapterService_ExecuteTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorAdapterServiceServer).ExecuteTransfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorAdapterService_CheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorAdapterServiceServer).CheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendorAdapterService_CheckStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorAdapterServiceServer).CheckStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VendorAdapterService_ServiceDesc is the grpc.ServiceDesc for VendorAdapterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VendorAdapterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "banking.adapter.v1.VendorAdapterService",
	HandlerType: (*VendorAdapterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTransfer",
			Handler:    _VendorAdapterService_ExecuteTransfer_Handler,
		},
		{
			MethodName: "CheckStatus",
			Handler:    _VendorAdapterService_CheckStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vendor_adapter.proto",
}
